version: "2.2"

services:
  gpn:
    build: "."
    container_name: gpn
    network_mode: host
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
    ports:
    - "0.0.0.0:10500:10500"

  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
